### ISSUE TITLE
Priority Checklist for Last Day.

### ISSUE THREAD

**Issue by comaldave** [TravelAmore/TravelAmore.github.io#16]
@CherylCrawford 
# Priority Checklist for Last Day.
### These things should be completed in the order given.
- [x] Complete the Word Document which contains the information about the site as defined in #1 .
> I used use a single-column layout for mobile, and then transition to a Holy Grail Layout with a header, footer, and center as a multi-column layout with two columns for tablets, three columns for laptops, four columns for desktop, and four columns limited to 1200px centered for large desktops. The layout is implemented by using flex boxes, percent-based element widths, use of relative units of measure (em, rem, vw, vh), and media break points at 600, 768, 992, and 1200 px.
- [x] Appropriate use of graphics (at least one per page) as required in #1 .
- - [x] Testimonials, suggest adding a face img above each h3. Select your faces from [uifaces.com](https://uifaces.com/).
- - [x] Privacy, suggest using [privacy-shield.png](https://pipl.com/corp/wp-content/uploads/2016/12/pipl-privacy-shield.png) at the top of the article, position it absolute to the right of the h3 h4 under the h2. You may have to change to width as well.
- - [x] Terms, [google for icon](https://www.google.com/search?q=icon+legal+terms&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwjFkKzvlfHaAhUL4YMKHVRCAY0Q7AkIXg&biw=1856&bih=1014) or use [Legal Notice Icon](https://cdn.xl.thumbs.canstockphoto.com/legal-notice-icon-internet-button-on-white-background-stock-illustration_csp27167585.jpg).
- [x] Complete the layout for mobile, tablet, and laptop using the media break points as required in #1 
- - [x] padding of text should be in rem instead of px for responsive design.
- - [x] margin should be in % instead of px for responsive design.
- [x] #15 Add photo and comment to home page.
- [x] For mobile, Chrome dev tools will be used to emulate and test the site on an iPhone 6 as required in #1 .
- [x] Validate CSS and HTML, have brackets add webkit.
- [x] Create a .zip of the HTML, CSS, and image files which make up your website.
- [x] Submit your zip file and doc file for your project.

**Comment by comaldave** [comment]
- [ ] Change center from 2 column to one column.
For phone and tablet you will need:
```
#center {
  flex-direction: column;
}
```
[How to js dropdown men on click](https://www.w3schools.com/howto/howto_js_dropdown.asp)

**Comment by Claire-Crawford** [comment]
Project completed and turned in.  Final grade 97%
